name = "utoa-photography"
main = ".open-next/cloudflare-worker.mjs"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run opennext"

# Bind routes to your domain. Ensure the zone exists in your Cloudflare account.
routes = [
  { pattern = "utoa.studio/*", zone_name = "utoa.studio" },
  { pattern = "www.utoa.studio/*", zone_name = "utoa.studio" }
]

[[d1_databases]]
binding = "DB"
database_name = "utoa-photography-db"
database_id = "1a65ccdb-72c0-4d12-aa72-65e4f639f06c"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "utoa-photography-assets"

[env.production]
name = "utoa-photography-prod"

[env.staging]
name = "utoa-photography-staging"
