name = "utoa-photography"
main = ".open-next/worker.js"
account_id = "5df67fbdc8e3dd0cc085b6f25dd15915"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]

## Build command is handled manually via `npm run opennext` before deploy
## to avoid re-running inside wrangler. Leave unset here.

# Bind routes to your domain. Ensure the zone exists in your Cloudflare account.
## Staging 不使用 routes（僅 workers.dev）。將 routes 搬到 production。

[[d1_databases]]
binding = "DB"
database_name = "utoa-photography-db"
database_id = "1a65ccdb-72c0-4d12-aa72-65e4f639f06c"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "utoa-photography-assets"

[env.production]
name = "utoa-photography-prod"
routes = [
  { pattern = "utoa.studio/*", zone_name = "utoa.studio" },
  { pattern = "www.utoa.studio/*", zone_name = "utoa.studio" }
]

[env.staging]
name = "utoa-photography"
workers_dev = true

[[env.staging.d1_databases]]
binding = "DB"
database_name = "utoa-photography-db"
database_id = "1a65ccdb-72c0-4d12-aa72-65e4f639f06c"

[[env.staging.r2_buckets]]
binding = "ASSETS"
bucket_name = "utoa-photography-assets"
