name = "utoa-photography"
main = ".open-next/cloudflare-worker.mjs"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[[d1_databases]]
binding = "DB"
database_name = "utoa-photography-db"
database_id = "your_database_id"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "utoa-photography-assets"

[env.production]
name = "utoa-photography-prod"

[env.staging]
name = "utoa-photography-staging"
